ТЗ 16: Added docker
Olhha/java-shareit pull request #4
Opened 2023-07-03 20:29 UTC by Olhha

2023-07-04 16:41 UTC, AnastasiyaFomkina requested changes
Отличная работа, молодец 🔥

2023-07-04 16:41 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String USER_ID_HEADER = "X-Sharer-User-Id";
Лучше вынести в отдельный класс и сделать публичной переменной, чтобы переиспользовать

2023-07-04 16:41 UTC, AnastasiyaFomkina commented on gateway/src/main/resources/application.properties
> +#logging.level.httpclient.wire=DEBUG
Закомментированные параметры нужно удалить

2023-07-04 16:41 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
Можно заменить конструктор и сеттер на аннотации `lombok`

2023-07-04 16:41 UTC, AnastasiyaFomkina commented on gateway/pom.xml
> +            <artifactId>spring-boot-starter-test</artifactId>
В данном модуле нет тестов, поэтому аннотация лишняя

2023-07-04 17:14 UTC, Olhha commented on gateway/pom.xml
> +            <artifactId>spring-boot-starter-test</artifactId>
done

2023-07-04 17:15 UTC, Olhha commented on gateway/src/main/resources/application.properties
> +#logging.level.httpclient.wire=DEBUG
done

2023-07-04 17:21 UTC, Olhha commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
done

2023-07-04 18:12 UTC, Olhha commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String USER_ID_HEADER = "X-Sharer-User-Id";
done

2023-07-05 00:09 UTC, AnastasiyaFomkina approved these changes

2023-07-05 02:28 UTC, merged